(() => {
  const KEY = "smartLearningAnnouncements";
  const RECIPIENT_KEY = "smartLearningAnnouncementRecipients";
  const TYPES = ["Exam", "Material", "Reminder", "Assignment", "Notice"];
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || "null") || fallback; } catch { return fallback; } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const teacherId = () => window.AttendanceService?.teacherId?.() || "local-teacher";
  const classes = () => window.AttendanceService?.loadTeacherClasses?.() || [];
  const subjects = (grade) => window.AttendanceService?.loadTeacherSubjects?.(grade) || [];
  const students = (grade) => window.AttendanceService?.loadRegisteredStudents?.(grade) || [];
  const client = () => window.SmartLearningSupabase?.getClient?.() || null;
  const now = () => new Date().toISOString();
  const normalize = (item) => ({ ...item, id: String(item.id || item.announcement_id), teacher_id: String(item.teacher_id || teacherId()), title: item.title || "Untitled announcement", message: item.message || item.description || "", type: item.type || "Notice", class_grade: String(item.class_grade || item.grade || ""), subject: item.subject || item.subject_id || "", audience: item.audience || "All students", priority: item.priority || "Normal", status: item.status || "Draft", published_at: item.published_at || null, scheduled_at: item.scheduled_at || null, created_at: item.created_at || now(), updated_at: item.updated_at || now(), attachment_url: item.attachment_url || "" });
  function localAnnouncements() { return read(KEY, []).map(normalize).filter((item) => item.teacher_id === teacherId()); }
  function promoteScheduled() { const records = read(KEY, []).map(normalize); let changed = false; records.forEach((item) => { if (item.teacher_id === teacherId() && item.status === "Scheduled" && item.scheduled_at && new Date(item.scheduled_at) <= new Date()) { item.status = "Published"; item.published_at = item.scheduled_at; item.updated_at = now(); changed = true; } }); if (changed) write(KEY, records); return records.filter((item) => item.teacher_id === teacherId()); }
  function recipientStudents(item) { return students(item.class_grade).filter((student) => { if (item.audience === "Selected students") return (item.recipient_ids || []).includes(String(student.student_id)); if (!item.subject) return true; const enrolled = String(student.subjects || student.subject || "").split(",").map((value) => value.trim()); return enrolled.includes(item.subject) || !enrolled.length; }); }
  function localRecipients(item) { const current = read(RECIPIENT_KEY, []); const existing = current.filter((row) => row.announcement_id !== item.id); return [...existing, ...recipientStudents(item).map((student) => ({ announcement_id: item.id, student_id: String(student.student_id), delivered_at: item.status === "Published" ? (item.published_at || now()) : null, read_at: current.find((row) => row.announcement_id === item.id && row.student_id === String(student.student_id))?.read_at || null }))]; }
  async function loadAnnouncements() { const supabase = client(); if (supabase) { const { data, error } = await supabase.from("announcements").select("*, announcement_recipients(*)").eq("teacher_id", teacherId()).order("created_at", { ascending: false }); if (error) throw error; return (data || []).map(normalize); } return promoteScheduled(); }
  async function saveAnnouncement(input) { const item = normalize({ ...input, id: input.id || `local-${Date.now()}`, teacher_id: teacherId(), updated_at: now(), created_at: input.created_at || now() }); const supabase = client(); if (supabase) { const { data, error } = await supabase.from("announcements").upsert(item, { onConflict: "id" }).select().single(); if (error) throw error; return data; } const records = read(KEY, []).map(normalize).filter((row) => row.id !== item.id || row.teacher_id !== teacherId()); write(KEY, [item, ...records]); write(RECIPIENT_KEY, localRecipients(item)); window.dispatchEvent(new CustomEvent("smart-learning-announcements-updated")); return item; }
  async function deleteAnnouncement(id) { const supabase = client(); if (supabase) { const { error } = await supabase.from("announcements").delete().eq("id", id).eq("teacher_id", teacherId()); if (error) throw error; return; } write(KEY, read(KEY, []).filter((item) => item.id !== id || item.teacher_id !== teacherId())); write(RECIPIENT_KEY, read(RECIPIENT_KEY, []).filter((row) => row.announcement_id !== id)); window.dispatchEvent(new CustomEvent("smart-learning-announcements-updated")); }
  async function getRecipients(announcements) { const supabase = client(); if (supabase) return announcements.flatMap((item) => item.announcement_recipients || []); return read(RECIPIENT_KEY, []).filter((row) => announcements.some((item) => item.id === row.announcement_id)); }
  function subscribe({ onChange }) { const supabase = client(); if (!supabase) { const handler = () => onChange(); window.addEventListener("smart-learning-announcements-updated", handler); window.addEventListener("storage", handler); return () => { window.removeEventListener("smart-learning-announcements-updated", handler); window.removeEventListener("storage", handler); }; } const channel = supabase.channel(`teacher-announcements-${teacherId()}`).on("postgres_changes", { event: "*", schema: "public", table: "announcements", filter: `teacher_id=eq.${teacherId()}` }, onChange).on("postgres_changes", { event: "*", schema: "public", table: "announcement_recipients" }, onChange).subscribe(); return () => supabase.removeChannel(channel); }
  window.AnnouncementService = { TYPES, classes, subjects, students, loadAnnouncements, saveAnnouncement, deleteAnnouncement, getRecipients, subscribe, teacherId };
})();
