(() => {
  const state = { materials: [], assignments: new Map(), user: null, type: "all", query: "", page: 1, pageSize: 8, provider: "local" };
  const $ = (id) => document.getElementById(id);
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
  const field = (item, names, fallback = "") => names.map((name) => item[name]).find((value) => value !== undefined && value !== null && value !== "") ?? fallback;
  const typeName = (type) => ({ pdf: "PDF", video: "Video", image: "Image", link: "Link", note: "Note", folder: "Folder", document: "Document" }[String(type).toLowerCase()] || String(type || "Document"));
  const normalizedType = (item) => String(field(item, ["type", "material_type", "file_type"], "document")).toLowerCase().replace("application/", "");
  const gradeOf = (value) => String(value ?? "").match(/\d+/)?.[0] || String(value ?? "");
  const materialUrl = (item) => field(item, ["file_url", "url", "external_url", "link_url", "storage_url"]);
  const toast = (message, kind = "") => { const element = document.createElement("div"); element.className = `toast ${kind}`; element.textContent = message; $("toastRegion").appendChild(element); setTimeout(() => element.remove(), 4000); };
  const formatSize = (bytes) => { if (!bytes) return "-"; const units = ["B", "KB", "MB", "GB"]; let index = 0; let amount = Number(bytes); while (amount >= 1024 && index < units.length - 1) { amount /= 1024; index += 1; } return `${amount.toFixed(index ? 1 : 0)} ${units[index]}`; };

  function assignmentsFromRegistration(registration) {
    const professional = registration?.professional || {};
    const map = new Map();
    const add = (grade, subject) => { if (!grade || !subject) return; const key = String(grade); if (!map.has(key)) map.set(key, new Set()); map.get(key).add(String(subject)); };
    const assignments = professional.specialistAssignments || professional.specialist_assignments || [];
    assignments.forEach((assignment) => (assignment.grades || []).forEach((grade) => add(grade, assignment.subject)));
    if (!assignments.length) {
      const groups = { grades_5_6: [5, 6], grades_7_8: [7, 8], grades_9_10: [9, 10], grades_11_12: [11, 12] };
      const standard = { 5: ["English", "Mathematics", "EVS", "Hindi"], 6: ["English", "Mathematics", "Science", "Social Science", "Hindi"], 7: ["English", "Mathematics", "Science", "Social Science", "Hindi"], 8: ["English", "Mathematics", "Science", "Social Science", "Hindi"], 9: ["English", "Mathematics", "Science", "Social Science", "Hindi"], 10: ["English", "Mathematics", "Science", "Social Science", "Hindi"] };
      const streams = { science_pcm: ["Physics", "Chemistry", "Mathematics"], science_pcb: ["Physics", "Chemistry", "Biology"], commerce: ["Accountancy", "Business Studies", "Economics"], arts_humanities: ["History", "Geography", "Political Science", "Psychology"] };
      const grades = professional.grades || professional.selected_grades || (professional.selected_grade_groups || []).flatMap((group) => groups[group] || []);
      const selectedSubjects = professional.subjects || professional.selected_subjects;
      grades.forEach((grade) => (Array.isArray(selectedSubjects) && selectedSubjects.length ? selectedSubjects : Number(grade) >= 11 ? [...new Set([...(professional.streams || professional.selected_streams || []).flatMap((stream) => streams[stream] || []), "English", "Physical Education", "Computer Science"])] : standard[Number(grade)] || []).forEach((subject) => add(grade, subject)));
    }
    return map;
  }

  function localKey() { return `teacherMaterials:${state.user?.id || "local-teacher"}`; }
  function localRead() { try { return JSON.parse(localStorage.getItem(localKey()) || "[]"); } catch { return []; } }
  function localWrite() { localStorage.setItem(localKey(), JSON.stringify(state.materials)); }
  function localProvider() { return { load: async () => { state.materials = localRead(); }, insert: async (item) => { state.materials.unshift({ ...item, id: `local-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, created_at: new Date().toISOString() }); localWrite(); }, remove: async (id) => { state.materials = state.materials.filter((item) => String(item.id) !== String(id)); localWrite(); } }; }
  function supabaseConfigured() { return Boolean(window.TeacherData?.getSupabaseClient?.()); }

  function renderAssignments() {
    const classSelect = $("materialClass"); const filter = $("classFilter");
    classSelect.innerHTML = '<option value="">Select a class</option>'; filter.innerHTML = '<option value="">All classes</option>';
    [...state.assignments.keys()].sort((a, b) => Number(a) - Number(b)).forEach((grade) => { classSelect.add(new Option(`Class ${grade}`, grade)); filter.add(new Option(`Class ${grade}`, grade)); });
    $("assignmentMessage").textContent = state.assignments.size ? "Only subjects assigned to your selected class are available." : "No teaching assignments were found. Add class and subject assignments to continue.";
    const scope = [...state.assignments.entries()].map(([grade, subjects]) => `Class ${grade} (${subjects.size} ${subjects.size === 1 ? "subject" : "subjects"})`).join("  •  ");
    $("assignmentScopeValue").textContent = scope || "No registered classes found";
  }
  function renderSubjects() { const grade = $("materialClass").value; const subjectSelect = $("materialSubject"); subjectSelect.innerHTML = '<option value="">Select a subject</option>'; subjectSelect.disabled = !grade; [...(state.assignments.get(grade) || [])].sort().forEach((subject) => subjectSelect.add(new Option(subject, subject))); $("assignmentMessage").textContent = grade && !state.assignments.get(grade)?.size ? "No subject is assigned to this class." : "Only subjects assigned to your selected class are available."; }
  function filteredMaterials() { const classFilter = $("classFilter").value; const subjectFilter = $("subjectFilter").value; const query = state.query.toLowerCase(); const rows = state.materials.filter((item) => { const type = normalizedType(item); const grade = gradeOf(field(item, ["class_grade", "grade", "class", "class_number"])); const subject = field(item, ["subject", "subject_name"], ""); const searchable = [field(item, ["title", "name"]), grade, subject, typeName(type), field(item, ["description"])].join(" ").toLowerCase(); return (state.type === "all" || type === state.type) && (!classFilter || classFilter === grade) && (!subjectFilter || subjectFilter === subject) && (!query || searchable.includes(query)); }); const sort = $("sortMaterials").value; return rows.sort((a, b) => { if (sort === "az") return field(a, ["title", "name"]).localeCompare(field(b, ["title", "name"])); if (sort === "za") return field(b, ["title", "name"]).localeCompare(field(a, ["title", "name"])); const aDate = new Date(field(a, ["created_at", "uploaded_at"])).getTime() || 0; const bDate = new Date(field(b, ["created_at", "uploaded_at"])).getTime() || 0; return sort === "oldest" ? aDate - bDate : bDate - aDate; }); }

  function render() {
    const all = filteredMaterials(); const start = (state.page - 1) * state.pageSize; const visible = all.slice(start, start + state.pageSize);
    $("materialsBody").innerHTML = visible.length ? visible.map((item) => { const type = normalizedType(item); const url = materialUrl(item); const title = field(item, ["title", "name"], "Untitled material"); const grade = gradeOf(field(item, ["class_grade", "grade", "class", "class_number"]), "-"); const date = field(item, ["created_at", "uploaded_at"]); return `<tr data-material-id="${escapeHtml(item.id)}"><td><a class="material-link" href="${escapeHtml(url || "#")}" ${url ? 'target="_blank" rel="noopener"' : ""}>${type === "folder" ? "📁" : "📄"} <span>${escapeHtml(title)}</span></a></td><td><span class="badge-type type-${escapeHtml(type)}">${escapeHtml(typeName(type))}</span></td><td>Class ${escapeHtml(grade)}</td><td>${escapeHtml(field(item, ["subject", "subject_name"], "-"))}</td><td>${date ? new Date(date).toLocaleString() : "-"}</td><td>${formatSize(field(item, ["file_size", "size", "size_bytes"], 0))}</td><td><span class="material-actions">${url ? `<a class="material-action" href="${escapeHtml(url)}" target="_blank" rel="noopener" title="Open">↗</a>` : ""}<button class="material-action" data-download="${escapeHtml(item.id)}" title="Open">↓</button><button class="material-action" data-delete="${escapeHtml(item.id)}" title="Delete">×</button></span></td></tr>`; }).join("") : '<tr><td class="empty-state" colspan="7"><strong>No materials found</strong>Try another search or upload your first material.</td></tr>';
    $("paginationSummary").textContent = all.length ? `Showing ${start + 1} to ${Math.min(start + state.pageSize, all.length)} of ${all.length} materials` : "No materials found";
    const pages = Math.ceil(all.length / state.pageSize); $("paginationControls").innerHTML = Array.from({ length: pages }, (_, index) => `<button class="page-btn ${index + 1 === state.page ? "active" : ""}" data-page="${index + 1}">${index + 1}</button>`).join("");
    const types = [null, "video", "pdf", "image", "folder"]; ["statTotal", "statVideos", "statPdfs", "statImages", "statFolders"].forEach((id, index) => { $(id).textContent = types[index] ? state.materials.filter((item) => normalizedType(item) === types[index]).length : state.materials.length; });
    const bytes = (type) => state.materials.filter((item) => !type || normalizedType(item) === type).reduce((sum, item) => sum + Number(field(item, ["file_size", "size", "size_bytes"], 0) || 0), 0); $("storageUsed").textContent = formatSize(bytes()); $("storageVideos").textContent = formatSize(bytes("video")); $("storagePdfs").textContent = formatSize(bytes("pdf")); $("storageImages").textContent = formatSize(bytes("image")); $("storageOthers").textContent = formatSize(bytes() - bytes("video") - bytes("pdf") - bytes("image"));
  }

  async function loadMaterials() { if (state.provider === "local") await localProvider().load(); else { const client = window.TeacherData.getSupabaseClient(); const result = await client.from("materials").select("*").eq("teacher_id", state.user.id).order("created_at", { ascending: false }); if (result.error) throw result.error; state.materials = result.data || []; } const subjects = [...new Set([...state.assignments.values()].flatMap((items) => [...items]))].sort(); $("subjectFilter").innerHTML = '<option value="">All subjects</option>'; subjects.forEach((subject) => $("subjectFilter").add(new Option(subject, subject))); render(); }
  async function removeMaterial(id) { if (!confirm("Delete this material permanently?")) return; try { if (state.provider === "local") await localProvider().remove(id); else { const { error } = await window.TeacherData.getSupabaseClient().from("materials").delete().eq("id", id).eq("teacher_id", state.user.id); if (error) throw error; state.materials = state.materials.filter((item) => String(item.id) !== String(id)); } render(); toast("Material deleted.", "success"); } catch (error) { toast(error.message || "Could not delete material.", "error"); } }
  function openMaterial(id) { const item = state.materials.find((material) => String(material.id) === String(id)); const url = item && materialUrl(item); if (url) window.open(url, "_blank", "noopener"); }
  function readFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }

  async function uploadMaterial(event) { event.preventDefault(); const type = $("materialType").value; const grade = $("materialClass").value; const subject = $("materialSubject").value; const file = $("materialFile").files[0]; if (!state.assignments.get(grade)?.has(subject)) return toast("Choose a class and assigned subject.", "error"); if (type !== "link" && !file) return toast("Choose a file to upload.", "error"); if (file && file.size > 25 * 1024 * 1024) return toast("Local files must be 25 MB or smaller.", "error"); const button = $("submitMaterial"); button.disabled = true; button.textContent = "Saving..."; try { const url = type === "link" ? $("materialLink").value.trim() : (file ? await readFile(file) : null); if (type === "link" && !url) throw new Error("Enter a valid URL."); const item = { teacher_id: state.user.id, title: $("materialTitle").value.trim(), description: $("materialDescription").value.trim(), type, class_grade: grade, subject, file_url: url, file_size: file?.size || 0, file_name: file?.name || "" }; if (!item.title) throw new Error("Enter a material title."); if (state.provider === "local") await localProvider().insert(item); else { const result = await window.TeacherData.getSupabaseClient().from("materials").insert(item); if (result.error) throw result.error; } $("materialForm").reset(); $("linkField").hidden = true; $("fileField").hidden = false; closeModal(); await loadMaterials(); toast("Material saved successfully.", "success"); } catch (error) { toast(error.message || "Could not save material.", "error"); } finally { button.disabled = false; button.textContent = "Save material"; } }
  function openModal() { $("materialModal").hidden = false; renderSubjects(); }
  function closeModal() { $("materialModal").hidden = true; }

  document.addEventListener("DOMContentLoaded", async () => { state.user = { id: "local-teacher" }; state.assignments = assignmentsFromRegistration(window.TeacherData?.getTeacherData?.() || {}); state.provider = supabaseConfigured() ? "supabase" : "local"; renderAssignments(); $("uploadMaterialBtn").addEventListener("click", openModal); $("newFolderBtn").addEventListener("click", () => toast("Folders are not available in local mode yet.", "error")); $("closeMaterialModal").addEventListener("click", closeModal); $("cancelMaterialModal").addEventListener("click", closeModal); $("materialClass").addEventListener("change", renderSubjects); $("materialType").addEventListener("change", () => { const link = $("materialType").value === "link"; $("linkField").hidden = !link; $("fileField").hidden = link; }); $("materialForm").addEventListener("submit", uploadMaterial); ["materialSearch", "classFilter", "subjectFilter", "sortMaterials"].forEach((id) => $(id).addEventListener("input", () => { state.query = $("materialSearch").value.trim(); state.page = 1; render(); })); document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".tab").forEach((item) => item.classList.remove("active")); tab.classList.add("active"); state.type = tab.dataset.type; state.page = 1; render(); })); $("materialsBody").addEventListener("click", (event) => { const deleteButton = event.target.closest("[data-delete]"); const openButton = event.target.closest("[data-download]"); if (deleteButton) removeMaterial(deleteButton.dataset.delete); if (openButton) openMaterial(openButton.dataset.download); }); $("paginationControls").addEventListener("click", (event) => { const button = event.target.closest("[data-page]"); if (button) { state.page = Number(button.dataset.page); render(); } }); try { await loadMaterials(); if (state.provider === "local") toast("Local mode enabled. Materials are saved in this browser.", "success"); } catch (error) { toast(error.message || "Could not load materials.", "error"); } });
  document.addEventListener("DOMContentLoaded", () => {
    $("materialFile")?.addEventListener("change", (event) => {
      $("fileName").textContent = event.target.files[0]?.name || "No file chosen";
    });
  });
})();
