(() => {
  const state = { quizzes: [], user: null, status: "all", query: "", page: 1, pageSize: 6 };
  const $ = (id) => document.getElementById(id);
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
  const valueOf = (item, names, fallback = "") => names.map((name) => item[name]).find((value) => value !== undefined && value !== null && value !== "") ?? fallback;
  const statusOf = (quiz) => String(valueOf(quiz, ["status"], "draft")).toLowerCase();
  const supabase = () => window.TeacherData?.getSupabaseClient?.();
  const toast = (message, kind = "") => { const node = document.createElement("div"); node.className = `quiz-toast ${kind}`; node.textContent = message; $("quizToastRegion").appendChild(node); setTimeout(() => node.remove(), 4000); };
  const formatDate = (value) => value ? new Date(value).toLocaleString() : "-";

  function filtered() {
    const query = state.query.toLowerCase(); const rows = state.quizzes.filter((quiz) => { const text = [valueOf(quiz, ["title", "name"]), valueOf(quiz, ["class_grade", "grade", "class"]), valueOf(quiz, ["subject"]), valueOf(quiz, ["topic", "chapter"])].join(" ").toLowerCase(); return (state.status === "all" || statusOf(quiz) === state.status) && (!query || text.includes(query)); });
    const sort = $("quizSort").value; return rows.sort((a, b) => { if (sort === "az") return valueOf(a, ["title", "name"]).localeCompare(valueOf(b, ["title", "name"])); if (sort === "za") return valueOf(b, ["title", "name"]).localeCompare(valueOf(a, ["title", "name"])); const left = new Date(valueOf(a, ["updated_at", "created_at"])).getTime() || 0; const right = new Date(valueOf(b, ["updated_at", "created_at"])).getTime() || 0; return sort === "oldest" ? left - right : right - left; });
  }

  function render() {
    const rows = filtered(); const start = (state.page - 1) * state.pageSize; const visible = rows.slice(start, start + state.pageSize); const body = $("quizTableBody");
    body.innerHTML = visible.length ? visible.map((quiz) => { const status = statusOf(quiz); const title = valueOf(quiz, ["title", "name"], "Untitled quiz"); const topic = valueOf(quiz, ["topic", "chapter"], "No topic"); const questions = valueOf(quiz, ["question_count"], 0); const responses = valueOf(quiz, ["response_count", "responses"], 0); const score = Number(valueOf(quiz, ["average_score", "avg_score"], 0)) || 0; const id = escapeHtml(quiz.id); return `<tr data-quiz-id="${id}"><td><div class="item-title"><div class="item-icon quiz-row-icon"><i class="fa-solid fa-clipboard-question"></i></div><div><div class="quiz-title-text">${escapeHtml(title)}</div><div class="quiz-subtitle-text">${escapeHtml(topic)}</div></div></div></td><td>Class ${escapeHtml(valueOf(quiz, ["class_grade", "grade", "class"], "-"))}</td><td>${escapeHtml(valueOf(quiz, ["subject"], "-"))}</td><td>${escapeHtml(questions)}</td><td>${escapeHtml(responses)}</td><td><div class="progress-bar-container"><span>${score}%</span><div class="progress-bar"><div class="progress-fill" style="width:${Math.min(100, score)}%"></div></div></div></td><td><span class="badge-status status-${escapeHtml(status)}">${escapeHtml(status[0].toUpperCase() + status.slice(1))}</span></td><td>${formatDate(valueOf(quiz, ["created_at", "updated_at"]))}</td><td><div class="action-icons"><a href="quiz-create.html?id=${id}" title="Edit"><i class="fa-solid fa-pen"></i></a><button data-delete="${id}" title="Delete"><i class="fa-solid fa-trash-can"></i></button></div></td></tr>`; }).join("") : '<tr><td class="quiz-empty-state" colspan="9"><strong>No quizzes found</strong>Create a quiz or adjust your search and filters.</td></tr>';
    $("quizPaginationSummary").textContent = rows.length ? `Showing ${start + 1} to ${Math.min(start + state.pageSize, rows.length)} of ${rows.length} quizzes` : "No quizzes found"; const pages = Math.ceil(rows.length / state.pageSize); $("quizPaginationControls").innerHTML = Array.from({ length: pages }, (_, index) => `<button class="page-btn ${index + 1 === state.page ? "active" : ""}" data-page="${index + 1}">${index + 1}</button>`).join("");
    $("quizTotal").textContent = state.quizzes.length; $("quizPublished").textContent = state.quizzes.filter((quiz) => statusOf(quiz) === "published").length; $("quizDrafts").textContent = state.quizzes.filter((quiz) => statusOf(quiz) === "draft").length; $("quizResponses").textContent = state.quizzes.reduce((sum, quiz) => sum + Number(valueOf(quiz, ["response_count", "responses"], 0) || 0), 0); const scored = state.quizzes.filter((quiz) => Number(valueOf(quiz, ["average_score", "avg_score"], 0)) > 0); $("quizAverage").textContent = `${scored.length ? Math.round(scored.reduce((sum, quiz) => sum + Number(valueOf(quiz, ["average_score", "avg_score"], 0)), 0) / scored.length) : 0}%`;
  }

  async function load() { const client = supabase(); if (!client || !state.user) { render(); toast("Supabase is not configured or you are not signed in.", "error"); return; } const result = await client.from("quizzes").select("*").eq("teacher_id", state.user.id).order("updated_at", { ascending: false }); if (result.error) throw result.error; state.quizzes = result.data || []; render(); }
  async function remove(id) { if (!confirm("Delete this quiz and its questions?")) return; const result = await supabase().from("quizzes").delete().eq("id", id).eq("teacher_id", state.user.id); if (result.error) return toast(result.error.message, "error"); state.quizzes = state.quizzes.filter((quiz) => String(quiz.id) !== String(id)); render(); toast("Quiz deleted.", "success"); }

  document.addEventListener("DOMContentLoaded", async () => { $("createQuizBtn")?.addEventListener("click", () => { window.location.href = "quiz-create.html"; }); $("questionBankBtn")?.addEventListener("click", () => toast("Question Bank is available inside the Create Quiz workflow.")); $("quizSearch").addEventListener("input", () => { state.query = $("quizSearch").value.trim(); state.page = 1; render(); }); $("quizSort").addEventListener("change", () => { state.page = 1; render(); }); document.querySelectorAll(".tab[data-status]").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".tab[data-status]").forEach((item) => item.classList.remove("active")); tab.classList.add("active"); state.status = tab.dataset.status; state.page = 1; render(); })); $("quizTableBody").addEventListener("click", (event) => { const button = event.target.closest("[data-delete]"); if (button) remove(button.dataset.delete); }); $("quizPaginationControls").addEventListener("click", (event) => { const button = event.target.closest("[data-page]"); if (button) { state.page = Number(button.dataset.page); render(); } }); const client = supabase(); if (!client) { render(); toast("Add the public Supabase key before connecting quiz data.", "error"); return; } const auth = await client.auth.getUser(); state.user = auth.data.user; if (!state.user) return toast("Sign in as a teacher to manage quizzes.", "error"); try { await load(); client.channel("teacher-quizzes").on("postgres_changes", { event: "*", schema: "public", table: "quizzes", filter: `teacher_id=eq.${state.user.id}` }, load).subscribe(); } catch (error) { toast(error.message || "Could not load quizzes.", "error"); } });
})();
